### ISSUE TITLE
Android Activity Graphs issue

### ISSUE THREAD

**Issue by ichrisanderson** [square/dagger#227]
Hi,

Ran into a few issues when trying to run the activity graph example.

There seems an issue with the DemoBaseFragment and rotation - the call to inject through onAttach results in a null pointer exception as the activity hasn't created the object graph yet.

Using onActivityCreated looks to solve this, is this the recommended point to use injection for fragments?

I've created a fork here: https://github.com/chrisanderson79/dagger/tree/master/examples/android-activity-graphs

**Comment by RowlandOti** [comment]
@adennie, your solution helped alot. Its obvious super.onCreate() does trigger something in Fragments.
