### ISSUE TITLE
Static analysis unable to find qualified provides method.

### ISSUE THREAD

**Issue by quenio** [square/dagger#289]
Hello,

The static analysis cannot find the provides method available for binding an qualified static field injection, and displays this error:

No binding for com...Type required by com...TypeWithStaticFields for com...Module

This issue only occurs with a clean compilation. If the qualified @Inject static field is added after a successful clean compilation, then the error does not occur.

I have observed this with a custom qualifier. I have not tried it with the @Named qualifier.

Also, if you add a provides method without a qualifier for the same type after getting this error, then compilation succeeds.

Thanks,
- Quenio

**Comment by JakeWharton** [comment]
Static injection was removed in #507 (and #509) for the next release.
