### ISSUE TITLE
Module adapter could not be loaded

### ISSUE THREAD

**Issue by jedikriks** [square/dagger#319]
So here is the Console output. I am using the same configuration as Android Bootstrap project, that is simple. I succeed to build and deploy the app to the device, but when i run it - it returns me an error always. Looks like it can not generate code for the annotations. I am using maven 3.X and JDK 1.7 (upd 40).

I already saw the same stacktrace on this issue tracker, but it did not help me at all.

I rly enjoy dagger features, but sofar i can not use them for real. Can you please help me with it?

Here is the stacktrace of the error:

E/AndroidRuntime( 9316): java.lang.RuntimeException: Unable to create application X: java.lang.IllegalStateException: Module adapter for X could not be loaded. Please ensure that code generation was run for this module.
E/AndroidRuntime( 9316):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4580)
E/AndroidRuntime( 9316):        at android.app.ActivityThread.access$1300(ActivityThread.java:153)
E/AndroidRuntime( 9316):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
E/AndroidRuntime( 9316):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9316):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 9316):        at android.app.ActivityThread.main(ActivityThread.java:5227)
E/AndroidRuntime( 9316):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 9316):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 9316):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime( 9316):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
E/AndroidRuntime( 9316):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 9316): Caused by: java.lang.IllegalStateException: Module adapter for class X could not be loaded. Please ensure that code generatio
was run for this module.
E/AndroidRuntime( 9316):        at dagger.internal.FailoverLoader.getModuleAdapter(FailoverLoader.java:41)
E/AndroidRuntime( 9316):        at dagger.internal.Modules.getAllModuleAdapters(Modules.java:43)
E/AndroidRuntime( 9316):        at dagger.ObjectGraph$DaggerObjectGraph.makeGraph(ObjectGraph.java:167)
E/AndroidRuntime( 9316):        at dagger.ObjectGraph$DaggerObjectGraph.plus(ObjectGraph.java:190)
E/AndroidRuntime( 9316):        at Y.init(Injector.java:13)
E/AndroidRuntime( 9316):        at Y.init(Injector.java:21)
E/AndroidRuntime( 9316):        at X.onCreate(InnComClientApp.java:43)
E/AndroidRuntime( 9316):        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
E/AndroidRuntime( 9316):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4577)
E/AndroidRuntime( 9316):        ... 10 more
W/ActivityManager(  518):   Force finishing activity my.package/.ui.MainActivity

**Comment by Kolyall** [comment]
@pabloogc Can you help me to make dagger:1.2.2 working on Android Studio? https://github.com/square/dagger/issues/520
