### ISSUE TITLE
NoClassDefFoundError on ObjectGraph

### ISSUE THREAD

**Issue by orira** [square/dagger#362]
Hi

I'm getting the following 
java.lang.NoClassDefFoundError: dagger.ObjectGraph when my app launches

I'm just trying to get dagger implemented into my app.  Ive disabled proguard as I thought this was at fault.  I'm using gradle as the build system, but can't seem to get around this issue, any help would be great.

Thanks

**Comment by Rogerp009** [comment]
Hello , I have a problem that is not how to fix it.

E/dalvikvm: Could not find class 'dagger.internal.FailoverLoader', referenced from method dagger.ObjectGraph.create
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: dagger.internal.FailoverLoader
at dagger.ObjectGraph.create(ObjectGraph.java:129)
