### ISSUE TITLE
Proposal: Dagger 2.0

### ISSUE THREAD

**Issue by gk5885** [square/dagger#366]
For a while now, we have floated ideas about full-graph generation and how we might evolve Dagger from half static, half runtime to a fully static, fully generated, fully awesome DI solution.  In working with Dagger in a large application on the server side we ran into some particular pain points that shaped how we might want a static solution to look.  So, I present a proposal for Dagger 2.0 that hopefully bridges the gaps between what's suitable on Android and what makes sense for very large applications, with ridiculous numbers of bindings.

https://docs.google.com/document/d/1fwg-NsMKYtYxeEWe82rISIHjNrtdqonfiHgp8-PQ7m8/edit?usp=sharing

Everybody should be able to comment.  Feedback on this bug and in the doc are both welcome.

I have also developed a prototype for this solution.  It works pretty well, but the code is still slightly embarrassing.  I will try to get that cleaned up and into a github repository shortly.  I'll update the bug when that happens.

**Comment by JakeWharton** [comment]
This happened.
