### ISSUE TITLE
Module Inclusion Cycle with addsTo

### ISSUE THREAD

**Issue by mattprecious** [square/dagger#370]
Maybe I'm misunderstanding how the graph works, but I'm getting cycle errors at compile-time when using `includes` and `addsTo` like so:

``` java
@Module(
  includes = {
    ChildModule.class
  })
public final class ParentModule {
  // ...
}
```

``` java
@Module(
  addsTo = ParentModule.class)
public final class ChildModule {
  // ...
}
```

It compiles and runs fine if I get rid of the `addsTo` attribute and add `complete = false, library = true` to both modules, but that's gross because it practically disables all the compile-time validation.

User error or bug?

**Comment by JoeMaher** [comment]
Still a massive help after all these years, thanks @mattprecious and @cgruber
