### ISSUE TITLE
Get the name from @Named in provider method

### ISSUE THREAD

**Issue by debdattabasu** [square/dagger#452]
Hi. 

Lets say I want to provide a named MongoDB collection. Currently, I do this: 

@Provides @Named("Collection1") 
DBCollection provide() {
   //get collection by name Collection1
}

@Provides @Named("Collection2") 
DBCollection provide() {
   //get collection by name Collection2
}

As you can see, this is just redundant boilerplate. Is there a way I can get the name from the named annotation so I can just write one provides method for all collections?

Regards, 
Debdatta Basu

**Comment by JakeWharton** [comment]
The names must be known statically (in the annotation processor running in the compiler) so there's no way of making it dynamic in this fashion. The only way to eliminate the code duplication would be to generate these provider methods with your own tool or annotation processor.
