### ISSUE TITLE
Injecting and inheritance

### ISSUE THREAD

**Issue by kaibookblue** [square/dagger#483]
Hi all,

In my Android project I have a class - MyBaseFragment - that extends android.app.Fragment and then a MyFragment class that extends MyBaseFragment.

I have a instance variable in MyBaseFragment that I want to @Inject into so I call objectGraph.inject(this) in the onCreate() method of MyBaseFragment and have "injects = MyBaseFragment.class" in my module.

However I am getting IllegalArgumentException saying that I have no inject registered for MyFragment.

Does Dagger not support injecting in the base class?  Will I have to list all the classes that inherit from MyBaseFragment in my module in the "injects" list?  Or am I doing something incredibly stupid?

(dagger and dagger-compiler 1.2.2)

Cheers,
Darren

**Comment by JakeWharton** [comment]
When you call `inject(this)`, even in the base class, the type of `this` is the subclass. Therefore `MyFragment` needs registered in an `injects=` list.

**Comment by kaibookblue** [comment]
So I was being incredibly stupid. :)

Thanks for the quick response.
