### ISSUE TITLE
Any plan for dagger extensions ?

### ISSUE THREAD

**Issue by fuhaiq** [square/dagger#487]
Any plan to implement extensions like 'Multibinder', 'MapBinder', 'Throwing Provider' ?

If so, then I can move to dagger ; )

**Comment by JakeWharton** [comment]
Set bindings and map bindings are already implemented.

**Comment by swankjesse** [comment]
ThrowingProviders were a mistake. The author was young and misguided.

**Comment by JakeWharton** [comment]
Oh wait this is Dagger 1. Set bindings exist, no map bindings.

**Comment by fuhaiq** [comment]
@JakeWharton So map bindings will exist in Dagger2 ?

**Comment by JakeWharton** [comment]
It already does, yes.

**Comment by fuhaiq** [comment]
@swankjesse ok, so just add 'throws' declaration in the provided method ? 
````java
@Provides Heater provideHeater() throws HeaterException{
  return new ElectricHeater();
}
````

**Comment by swankjesse** [comment]
@fuhaiq yeah, that'll work. The problem is that when you call `Provider.get()` later, that can throw an unchecked exception.

**Comment by fuhaiq** [comment]
That's quite enough for what I want to know, please close this issue if anyone could.
