### ISSUE TITLE
Why Dagger does not support method injection ?

### ISSUE THREAD

**Issue by fuhaiq** [square/dagger#488]
I am going to move to Dagger2, and my project is currently using method injection for session control and interception.(I think this makes codes flexible)

But I notice that Dagger does not support AOP. Is there any outstanding reason for this ?

**Comment by JakeWharton** [comment]
There's no need to bake AOP into a DI library. Libraries like AspectJ are already very good at AOP and can be used in conjunction with Dagger 1 & 2.

https://groups.google.com/d/msg/dagger-discuss/pSSejx7s5h8/HKzwuJh-ZJYJ

**Comment by fuhaiq** [comment]
@JakeWharton thanks for quick response, that makes sense, I will take a look.
