### ISSUE TITLE
@Named providers with same return types end up giving java.lang.IllegalArgumentException: Duplicate

### ISSUE THREAD

**Issue by AlicanHasirci** [square/dagger#490]
As i have explained in this stackoverflow link(http://stackoverflow.com/questions/31581183/named-providers-with-same-return-types-end-up-giving-java-lang-illegalargumente), i am facing an issue where nearly identical modules create different behaviours. There were a lot a views on stackoverflow link but no remedy yet so i figured it would be convenient to post it here.

**Comment by swankjesse** [comment]
Tracking on stackoverflow.
