### ISSUE TITLE
Make Lazy Serializable

### ISSUE THREAD

**Issue by cizmazia** [square/dagger#491]
Is there a reason for not making `Lazy` to be `Serializable` in the same way as Guava `Suppliers`?

This would make it straightforward to use with frameworks which serialize lambdas (with lazy dependencies) to execute them in a different process.

**Comment by JakeWharton** [comment]
There's no guarantee the the `T` in `Lazy<T>` is `Serializable`. Plus, if you serialize and then deserialize an instance of `Lazy<T>` which never fetched the backing `T`, how is it supposed to fetch that value without being bound to the backing graph?

**Comment by cizmazia** [comment]
I use the following pattern with Guava [Suppliers](https://www.codatlas.com/github.com/google/guava/master/guava/src/com/google/common/base/Suppliers.java?keyword=Guava+Suppliers&line=107) (for variables used in lambdas which are serialized and executed by Apache Spark in different processes):

```java
final Supplier<MyObj> supplier = (Serializable & Supplier<MyObj>) () -> new MyObj();
final Supplier<MyObj> lazy = Suppliers.memoize(supplier);
```

It seems that [Lazy](https://www.codatlas.com/github.com/square/dagger/master/core/src/main/java/dagger/internal/LazyBinding.java?line=49) can be implemented in the same way as [MemoizingSupplier](https://www.codatlas.com/github.com/google/guava/master/guava/src/com/google/common/base/Suppliers.java?keyword=Guava+Suppliers&line=114). In my use case, this would eliminate the boilerplate code above.

**Comment by swankjesse** [comment]
We can't support this in a reasonable way. It breaks many assumptions and I don't think your cute sample is worth the hidden complexities it carries.

One simple assumption: if any dependency of the lazy is a stateful singleton, do we get two instances upon deserialization?

**Comment by cizmazia** [comment]
For this kind of use cases, that is exactly the expected guarantee: one singleton instance per process.

**Comment by cizmazia** [comment]
It is not about my cute sample. As far as I can tell this a simplest approach for dependency injection into lambdas which are being distributed into multiple Apache Spark workers. Any pointers appreciated.
