### ISSUE TITLE
Getting java.lang.NoClassDefFoundError if package name is different than applicationId

### ISSUE THREAD

**Issue by gabrielsoroush** [square/dagger#493]
I just created a new flavor in my gradle file with a new applicationId, but my app crashes when I'm trying to inject a class. It throws this exception:

java.lang.NoClassDefFoundError

It seems that it's still looking at the default applicationId and package name. I only see this issue on Kitkat and below.
Please let me know if you need more information about this issue.

**Comment by JakeWharton** [comment]
We need a lot more information as you've given almost none. Dagger doesn't
care what your application ID or package name is—it knows nothing about
Android. You need to provide a full stack trace, show your graph creation
and module code, and/or create a sample that demonstrates the problem.

**Comment by gabrielsoroush** [comment]
Thanks Jake for your quick response. Unfortunately I can't share any code here.
But after reading this: https://code.google.com/p/android/issues/detail?id=75456 I figured it might be the gradle issue not Dagger.

**Comment by JakeWharton** [comment]
Ok. Without more info there's no action for us to take then.
