### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by GeorgeGathura** [square/dagger#494]
I'm fairly new to android and i'm trying to use dagger. i downloaded both jars,included java poet & javax.inject but i'm still getting this error whenever gradle builds(Android studio)

Error:Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider dagger.internal.codegen.ModuleAdapterProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/squareup/javawriter/JavaWriter

my dependencies{
  compile 'javax.inject:javax.inject:1'
    compile 'com.squareup:javapoet:1.2.0'
    provided files('libs/dagger-compiler-1.2.2.jar')
    compile files('libs/dagger-1.2.2.jar')
}
i know i've probably missed something, pls help

**Comment by JakeWharton** [comment]
You are missing the JavaWriter dependency that the compiler requires.

**Comment by GeorgeGathura** [comment]
i added it and worked. 
Thanks.

**Comment by JakeWharton** [comment]
#458 switched Dagger to JavaPoet.
