### ISSUE TITLE
Dagger 2: NoClassDefFoundError: dagger/producers/ProducerModule

### ISSUE THREAD

**Issue by jagbirsingh125** [square/dagger#495]
up vote
0
down vote
favorite
I am trying to integrate Dagger 2 with eclipse and the libs that I have used are as follows:

dagger-2.0.jar
dagger-compiler-2.0.jar
guava-13.0.1.jar
javawriter-1.0.5.jar
javax.annotation-api-1.2.jar
javax.inject-1.jar
Java Compiler -> Annotation processing has been enabled All the above have been added to the Factory Path

But I get the following error when I build the project: Description Resource Path Location Type

Internal compiler error: java.lang.NoClassDefFoundError: dagger/producers/ProducerModule at dagger.internal.codegen.ComponentProcessor.initSteps(ComponentProcessor.java:90)    BuildConfig.java    /DIDemo/gen/com/example/didemo  line 0  Java Problem
Could someone please help?

**Comment by JakeWharton** [comment]
Dagger 2 is here: https://github.com/google/dagger.
