### ISSUE TITLE
Example simple build fail

### ISSUE THREAD

**Issue by gengjiawen** [square/dagger#498]
I try build the simple module in the examples folder.but i failed.here is the output:
```ShellSession
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Examples: Simple 1.2.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.squareup.dagger:dagger-compiler:jar:1.2.3-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
So i checked dagger-compiler the maven (http://mvnrepository.com/artifact/com.squareup.dagger/dagger-compiler), and the version 1.2.3-SNAPSHOT is not there.Will you guys fix this?

**Comment by tbroyer** [comment]
1.2.3-SNAPSHOT is the current version at `master`, so either do an `mvn install` at the root of your Git clone, or use `mvn -pl examples/simple -am package` (using `package` here as an example goal). That said running Maven at the root of the Git clone *will* build the example as part of the reactor/multi-module build.

That said, by total chance, you're right there was a problem uploading the `dagger-compiler` during the last build: https://travis-ci.org/square/dagger/builds/87551853#L1484 (but it's a snapshot so mvnrepository wouldn't show it anyway)

**Comment by gengjiawen** [comment]
@tbroyer It works when i use the command ```mvn install clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true```from travis.Thanks.
