### ISSUE TITLE
Consider constructor auto-generation to allow private field injection.

### ISSUE THREAD

**Issue by vackosar** [square/dagger#518]
For example in ``` class A { @Inject private B b; } ``` field ```b``` cannot be injected because it is private field.

Can you please consider to automatically generate constructor into class ```A``` upon compilation to avoid having to make ```b``` more accessible or writing constructor manually?

**Comment by JakeWharton** [comment]
Annotation processing cannot modify existing classes. This cannot be done
for that reason alone, among others.

**Comment by vackosar** [comment]
Well AspectJ does code generation at compile time, so it can be done, no?

**Comment by JakeWharton** [comment]
Byte code rewriting is a very different thing than annotation processing,
though. And Dagger has no way of interacting with code at the bytecode
level.
