### ISSUE TITLE
Holding reference after onDestroy() 

### ISSUE THREAD

**Issue by jemshit** [square/dagger#519]
**Question:** does Dagger remove reference to injected variables on `onDestroy()` of Activity ? [Here](https://github.com/ribot/android-boilerplate/pull/31) a guy wrote Activity holds reference to injected `Presenter`variable after Activity is destroyed. Someone enlighten me, thanks.

**Comment by JakeWharton** [comment]
Dagger knows nothing about Android and thus nothing about the Android activity lifecycle. Injected types are not automatically freed.

However, you interpreted that issue incorrectly. It is the presenter which is keeping a reference to the activity and preventing the activity from being garbage collected, not the other way around.

**Comment by jemshit** [comment]
So we make each injectedVariable=null  on onDestroy() or any other quick
solution to prevent memory leak?

**Comment by JakeWharton** [comment]
There is no leak. If the activity has outgoing references to dependencies and there are no incoming references to the activity it will be garbage collected.

**Comment by jemshit** [comment]
Ok, so the problem was Presenter keeping ref to Activity. Thanks :+1:

**Comment by jemshit** [comment]
One last question, after Activity is destroyed and so its Presenter is garbage collected, does Presenter still can hold references even it is garbage collected?

**Comment by JakeWharton** [comment]
No. Once garbage collected an object doesn't hold any references.

**Comment by jemshit** [comment]
I guess the thing i missed is `Activity is destroyed` does not mean it is garbage collected.
