### ISSUE TITLE
dagger-compiler:1.3.0-SNAPSHOT not on Sonatype

### ISSUE THREAD

**Issue by AngusMorton** [square/dagger#523]
It looks like the `dagger:1.3.0-SNAPSHOT` is available on Sonatype, however the `dagger-compiler:1.3.0-SNAPSHOT` is not available, as far as I can see.

https://oss.sonatype.org/content/repositories/snapshots/com/squareup/dagger/dagger/
https://oss.sonatype.org/content/repositories/snapshots/com/squareup/dagger/dagger-compiler/

```groovy
apt 'com.squareup.dagger:dagger-compiler:1.3.0-SNAPSHOT'
compile 'com.squareup.dagger:dagger:1.3.0-SNAPSHOT'
```

Have I missed something?

**Comment by JakeWharton** [comment]
The build is failing halfway through when it tries to upload. I'll look
later.
