### ISSUE TITLE
你好，请问有没有中文版的wiki

### ISSUE THREAD

**Issue by zhanjixun** [square/dagger#525]

**Comment by JakeWharton** [comment]
We don't have a wiki. Do you mean the website?

**Comment by zhanjixun** [comment]
嗯，你好，有中文版的主页吗，我的英文阅读能力有点差。

**Comment by Freedom000** [comment]
@JakeWharton  Well，he means some description in Chinese just like wiki or papers and so on.

**Comment by JakeWharton** [comment]
@zhanjixun No problem. 我的中国更糟糕的是 (Google Translated)

@Freedom000 ah, thanks. I'm sure there's a Chinese introduction on a website or blog somewhere, but I do not know of any.

**Comment by soarcn** [comment]
There are many of them, for example http://blog.changecong.com/2014/12/daggerjianjiezhongwen/

try to search "dagger 中文 android" in google or baidu.

**Comment by JakeWharton** [comment]
I'll defer to the search then. We're certainly not going to be able to produce any better. Thanksm
