### ISSUE TITLE
class dagger.shaded.auto.common.MoreTypes$1 has interface com.google.common.base.Equivalence as super class

### ISSUE THREAD

**Issue by MakerYan** [square/dagger#526]
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IncompatibleClassChangeError: class dagger.shaded.auto.common.MoreTypes$1 has interface com.google.common.base.Equivalence as super class

**Comment by JakeWharton** [comment]
Dagger 1's compiler does not shade Guava. You probably want https://github.com/google/dagger.

**Comment by tbroyer** [comment]
@JakeWharton This is about auto-common, not Guava; but that doesn't change your answer: Dagger 1 doesn't use auto-common.
