### ISSUE TITLE
the initial files of Dagger have already generated, but it couldn't be found when  compiled

### ISSUE THREAD

**Issue by qq4105195** [square/dagger#537]
符号: 类 FragmentPostBinding
C:\Users\yufei\Desktop\gitWork\qiQiaoGuo\v2T\Android_qiqiaoguo_v2\app\src\main\java\com\platomix\qiqiaoguo\ui\activity\PostDetailActivity.java:50: 错误: 程序包com.platomix.qiqiaoguo.databinding不存在
import com.platomix.qiqiaoguo.databinding.ActivityPostDetailBinding;
                                         ^
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.AddTopicActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.AgencyActivity. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.AgencyAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.AgencyDetailActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.fragment.BlankFragment. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.MyAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.adapter.MyAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.ChooseCircleActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.CircleAllActivity. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.CircleAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.adapter.CircleAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.fragment.CircleFragment. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.HotTopicAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.CircleDetailActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.fragment.CommunityFragment. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.EducationCategoryActivity. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.EducationNavigationAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.adapter.EducationNavigationAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.fragment.EducationCategoryDetailFragment. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.fragment.EducationFragment. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.SubjectAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.RecommendActiveAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.RecommendVideoAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.RecommendEducationCategoryAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.FloorDetailActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.fragment.FollowPostFragment. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.FollowPostAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.adapter.FollowPostAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.fragment.HotPostFragment. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.PostAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.adapter.PostAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.MainActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.fragment.PostFragment. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.PostDetailActivity. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.PostCommentAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.PublishActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.SubjectActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.SubjectDetailActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.TeacherActivity. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.TeacherAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.TopicAllActivity. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.ui.adapter.TopicAdapter. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.TopicActivity. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.fragment.TopicPostFragment. Prefer to run the dagger processor over that class instead.
注: Generating a MembersInjector for com.platomix.qiqiaoguo.ui.activity.UserListActivity. Prefer to run the dagger processor over that class instead.
注: Generating a Provider for com.platomix.qiqiaoguo.model.UserListAdapter. Prefer to run the dagger processor over that class instead.
警告: Application namespace for attribute bind:url will be ignored.

 FAILED
:app:compileRetrolambdaDebug UP-TO-DATE

FAILURE: Build failed with an exception.

**Comment by JakeWharton** [comment]
The issue is from data binding, not Dagger. The warnings are because you are not running the compiler in the library where the listed types are present.
