### ISSUE TITLE
Does Dagger works with the new Jack compiler toolchain?

### ISSUE THREAD

**Issue by chakrit** [square/dagger#538]
See here: https://developer.android.com/preview/j8-jack.html

Relevant? quote:

> Because Jack does not generate intermediate class files when compiling an app, tools that depend on these files do not currently work with Jack. Some examples of these tools are:

I'm converting an old project which uses `dagger-compiler` and `gradle-retrolambda` to this new Jack thing so I can get rid of the retrolambda hack and having hard time getting the `compileDebugJavaWithJack` task to finish so was wondering if this was the issue.

**Comment by JakeWharton** [comment]
Yes. You use `annotationProcessor` to declare the `dagger-compiler` artifact. More info @ http://tools.android.com/tech-docs/jackandjill

**Comment by chakrit** [comment]
@JakeWharton oh, that page is certinaly much more useful. Thank you!!
