### ISSUE TITLE
looking for contributor for jBeanBox Android project 

### ISSUE THREAD

**Issue by drinkjava2** [square/dagger#541]
Hi I'm newbie in Android,  if some one have interest develop Android version of jBeanBox can take a look of this project (search jBeanBox in Github), it's a simple IOC/AOP tool(only 1 file ~1000 lines source code) aim to replace Spring in small projects, It uses Java as configuration(called "BeanBox") but easier to use than Spring or Guice's Java-based configurations.

**Comment by JakeWharton** [comment]
I'm afraid this isn't a good forum for such a search. This project is on long-term support, not active development.

**Comment by drinkjava2** [comment]
Hi Jake,
Thank you take time to replay this issue.

Best Regards
Yong Zhu

2016-07-24 17:17 GMT-06:00 Jake Wharton <notifications@github.com>:
