### ISSUE TITLE
java.lang.NoClassDefFoundError: dagger.internal.Preconditions

### ISSUE THREAD

**Issue by ifucolo** [square/dagger#550]
I have that problem with android 4.3
Im using dagger 2 on my buildgradle like this:
    apt 'com.google.dagger:dagger-compiler:2.5'
    compile 'com.google.dagger:dagger:2.5'

**Comment by tbroyer** [comment]
Wrong issue tracker then; see https://github.com/google/dagger

**Comment by ifucolo** [comment]
I m using Multidex.install on my application
Thanks
