### ISSUE TITLE
android.app.Application does not implement dagger.android.HasActivityInjector

### ISSUE THREAD

**Issue by kingning1** [square/dagger#552]
public class Myapp extends DaggerApplication implements HasActivityInjector {

    @Inject
    DispatchingAndroidInjector<Activity> activityDispatchingAndroidInjector;

    @Override
    public void onCreate() {
        super.onCreate();
    }

    @Override
    protected AndroidInjector<? extends DaggerApplication> applicationInjector() {
        return DaggerAppComponent.builder().create(this);
    }

    @Override
    public DispatchingAndroidInjector<Activity> activityInjector() {
        return activityDispatchingAndroidInjector;
    }
}

这是我的Application 但是每次运行都会报这个错误很是不解，求救！

**Comment by JakeWharton** [comment]
You need to specify your application subclass in the manifest on the `<application>` tag.

**Comment by kingning1** [comment]
不好意思，疏忽大意了！
谢谢您在百忙之中的帮助。

**Comment by JakeWharton** [comment]
Just noticed that I think you want https://github.com/google/dagger/ and not this repo. Dagger 1 doesn't have `HasActivityInjector`.
