### ISSUE TITLE
Subcomponent inside subcomponent

### ISSUE THREAD

**Issue by RakeshTM** [square/dagger#556]
After the new Android studio latest stable update, it is not able to use Subcomponent inside subcomponent. 

Sample project : https://github.com/vestrel00/android-dagger-butterknife-mvp.git

Android Studio Details : Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by NightlyNexus** [comment]
Wrong Dagger. github.com/google/dagger is component Dagger.
