### ISSUE TITLE
Why do Singletons need an empty default constructor?

### ISSUE THREAD

**Issue by Isabaellchen** [square/dagger#562]
Sorry for piling onto the empty default constructor debate, but this is something i do not understand.

I do understand that you want to make the code explicit as to where classes get initialized, but i do not understand why this has to be the case for classes that are annotated as Singletons, since there is only that one particular instance that i want to create.
If it is not too much to ask maybe someone could give an explanation to this?

**Comment by JakeWharton** [comment]
I think you want google/dagger

**Comment by Isabaellchen** [comment]
Sorry
