### ISSUE TITLE
duplicate Nullable

### ISSUE THREAD

**Issue by byrxs5216** [square/dagger#572]

**Comment by byrxs5216** [comment]
@Generated("dagger.hilt.android.processor.internal.androidentrypoint.ViewGenerator")
public abstract class Hilt_SeltDefHiltViewLib1 extends AppCompatTextView implements GeneratedComponentManager<Object> {
  private ViewComponentManager componentManager;

  Hilt_SeltDefHiltViewLib1(@NonNull Context arg0) {
    super(arg0);
    inject();
  }

  Hilt_SeltDefHiltViewLib1(@NonNull Context arg0, @Nullable @Nullable AttributeSet arg1) {
    super(arg0, arg1);
    inject();
  }

  Hilt_SeltDefHiltViewLib1(@NonNull Context arg0, @Nullable @Nullable AttributeSet arg1, int arg2) {
    super(arg0, arg1, arg2);
    inject();
  }

  @Override
  public final Object generatedComponent() {
    return componentManager().generatedComponent();
  }

  protected ViewComponentManager createComponentManager() {
    return new ViewComponentManager(this, false /* hasFragmentBindings */);
  }

  protected final ViewComponentManager componentManager() {
    if (componentManager == null) {
      componentManager = createComponentManager();
    }
    return componentManager;
  }

  protected void inject() {
    ((SeltDefHiltViewLib1_GeneratedInjector) generatedComponent()).injectSeltDefHiltViewLib1(UnsafeCasts.<SeltDefHiltViewLib1>unsafeCast(this));
  }
}

**Comment by JakeWharton** [comment]
Wrong Dagger project. Try https://github.com/google/dagger.
